Updated avatar Indigo.Design System section
IgniteUI/indigo-design-docfx pull request #374
Opened 2020-12-10 14:43 UTC by YoannaIvanova

2020-12-14 12:05 UTC, StefanIvanov requested changes

2020-12-14 12:05 UTC, StefanIvanov commented on en/components/avatar.md
> +
```suggestion

## Shape

The avatar comes in two distinct types determined by its shape: a **round** and a **square** form.

<img class="responsive-img" src="../images/avatar_type.png" srcset="../images/avatar_type@2x.png 2x" />

```

2020-12-14 12:05 UTC, StefanIvanov commented on en/components/avatar.md
> +
Once you accept the Shape heading move the section for shape after the one for size.

2020-12-14 15:56 UTC, StefanIvanov approved these changes

2020-12-17 11:31 UTC, sdimchevski approved these changes

2021-01-07 12:15 UTC, merged