Updated carousel Indigo.Design System section
IgniteUI/indigo-design-docfx pull request #376
Opened 2020-12-10 16:21 UTC by YoannaIvanova

2020-12-14 12:32 UTC, StefanIvanov requested changes

2020-12-14 12:32 UTC, StefanIvanov commented on en/components/carousel.md
```suggestion

## Indicators and Slides

The Carousel lets you define up to 10 slides, where for each one there is a matching indicator dot, allowing the user to navigate to that respective slide.

```

2020-12-14 12:32 UTC, StefanIvanov commented on en/components/carousel.md
>  ## Styling
@YoannaIvanova add an image for the section above showing a default slider with the 10 dots and some image that you like :)

2020-12-14 12:32 UTC, StefanIvanov commented on en/components/carousel.md
@YoannaIvanova  add an image for this section showing a default slider with 10 dots and just use some image that you like :)

2020-12-14 16:02 UTC, StefanIvanov requested changes

2020-12-14 16:02 UTC, StefanIvanov commented on en/components/carousel.md
> +
I think we need to update all images for this topic except for the dos and donts

2020-12-14 16:03 UTC, StefanIvanov commented on en/components/carousel.md
> +
And also add an image after this section that is new.

2020-12-15 08:28 UTC, StefanIvanov approved these changes

2020-12-17 13:31 UTC, sdimchevski reviewed
Please fix the path for the Retina image here:
scrset="..images/carousel_indicators&slides@2x.png 2x"
should be:
scrset="../images/carousel_indicators&slides@2x.png 2x"

2020-12-18 08:37 UTC, YoannaIvanova commented
> Please fix the path for the Retina image here:
> scrset="..images/carousel_indicators&[slides@2x.png](mailto:slides@2x.png) 2x"
> should be:
> scrset="../images/carousel_indicators&[slides@2x.png](mailto:slides@2x.png) 2x"

Fixed

2020-12-18 11:04 UTC, sdimchevski approved these changes

2021-01-07 12:16 UTC, merged