Updated dialog topic
IgniteUI/indigo-design-docfx pull request #395
Opened 2020-12-16 10:53 UTC by YoannaIvanova

2020-12-16 14:41 UTC, StefanIvanov requested changes

2020-12-16 14:41 UTC, StefanIvanov commented on en/components/dialog.md
> +The Dialog comes with styling flexibility through the various overrides for its title and message, the buttons at the bottom with all the styling options that [Button](button.md) component provide, a
```suggestion
The Dialog comes with styling flexibility through the various overrides for its title and message, the buttons at the bottom with all the styling options that [Button](button.md) component provides, as well as the background and elevation.
```

2020-12-16 14:41 UTC, StefanIvanov commented on en/components/dialog.md
> +When designing a custom Dialog, avoid placing buttons in the body section and use the existing dialog buttons for your actions instead of new ones.
```suggestion
When designing a custom Dialog, avoid placing buttons in the body section and use the existing dialog buttons for your actions instead.
```

2021-01-04 15:24 UTC, StefanIvanov approved these changes

2021-01-08 10:07 UTC, sdimchevski approved these changes

2021-01-08 12:06 UTC, merged