Updated navbar topic
IgniteUI/indigo-design-docfx pull request #406
Opened 2020-12-16 16:39 UTC by YoannaIvanova

2020-12-17 09:01 UTC, StefanIvanov requested changes

2021-01-04 15:12 UTC, StefanIvanov requested changes

2021-01-04 15:12 UTC, StefanIvanov commented on en/components/navbar.md
> +//@Yoanna should add sample images here
We are still missing the two images here for elevated and outlined

2021-01-06 11:21 UTC, StefanIvanov approved these changes

2021-01-08 10:19 UTC, sdimchevski approved these changes

2021-01-08 12:11 UTC, merged