Updated nav-drawer topic
IgniteUI/indigo-design-docfx pull request #407
Opened 2020-12-17 10:11 UTC by YoannaIvanova

2020-12-17 13:58 UTC, StefanIvanov requested changes

2020-12-17 13:58 UTC, StefanIvanov commented on en/components/nav-drawer.md
> +The Navigation Drawer supports a **default** type with icon and label for each item and a mini type with icons only. If your design contains five or less items/views, you may pick between Navigation
```suggestion
The Navigation Drawer supports a **default** type with icon and label for each item and a mini type with icons only. If your design contains five or less items/views, you may want to consider using a [Bottom Navigation](bottom-nav.md) instead.
```

2020-12-17 13:58 UTC, StefanIvanov commented on en/components/nav-drawer.md
> +//@Yoanna add three images for the states
@YoannaIvanova add an image here

2020-12-17 13:58 UTC, StefanIvanov commented on en/components/nav-drawer.md
> +//@Yoanna add another dont with two active items
@YoannaIvanova add another do/dont here

2021-01-06 11:54 UTC, StefanIvanov approved these changes

2021-01-08 10:24 UTC, sdimchevski approved these changes

2021-01-08 12:13 UTC, merged