Updated radio group topic
IgniteUI/indigo-design-docfx pull request #409
Opened 2020-12-17 15:47 UTC by YoannaIvanova

2021-01-07 12:36 UTC, StefanIvanov requested changes

2021-01-07 12:36 UTC, StefanIvanov commented on en/components/radio-group.md
> +
```suggestion
The Radio Group can be inserted in an enabled or disabled state.

<img class="responsive-img" src="../images/radiogroup_enabled-state.png" srcset="../images/radiogroup_enabled-state@2x.png 2x" />
<img class="responsive-img" src="../images/radiogroup_disabled-state.png" srcset="../images/radiogroup_disabled-state@2x.png 2x" />

You may also set the state of a radio button in the group to disabled to disallow user interaction with it.

<img class="responsive-img" src="../images/radiogroup_enabled&disabled-state.png" srcset="../images/radiogroup_enabled&disabled-state@2x.png 2x" />

```

2021-01-07 12:36 UTC, StefanIvanov commented on en/components/radio-group.md
> +When extending a Radio Group with additional items, make sure that they are all vertically left-aligned in a single column. Avoid layout in multiple columns, as well as situations with more than one
```suggestion
When extending a Radio Group with additional items, make sure that they are aligned consistently and form a single column. Avoid layout in multiple columns, as well as situations with more than one Radio element with on state at a time.
```

2021-01-08 10:18 UTC, StefanIvanov approved these changes

2021-01-08 10:40 UTC, sdimchevski approved these changes

2021-01-08 12:14 UTC, merged