Updated slider topic
IgniteUI/indigo-design-docfx pull request #410
Opened 2020-12-18 10:43 UTC by YoannaIvanova

2021-01-04 13:30 UTC, StefanIvanov requested changes

2021-01-04 13:30 UTC, StefanIvanov commented on en/components/slider.md
> +The Slider allows to choose from two types - continuous and discrete. They each offer a variant with one thumb for selecting a single value and with two thumbs for specifying a range.
Take out the one and two thumbs and place them in a separate sub-section. 
Move the state section for enabled and disabled after it and then continue with theme and styling.

2021-01-07 10:25 UTC, StefanIvanov approved these changes

2021-01-08 10:43 UTC, sdimchevski requested changes

2021-01-08 10:43 UTC, sdimchevski commented on en/components/slider.md
> +The Slider allows to choose from two types - continuous and discrete.
```suggestion
The Slider allows the user to choose from two types - continuous and discrete.
```

2021-01-08 11:31 UTC, sdimchevski approved these changes

2021-01-08 12:13 UTC, merged