Updated snackbar topic
IgniteUI/indigo-design-docfx pull request #411
Opened 2020-12-18 12:14 UTC by YoannaIvanova

2021-01-04 15:50 UTC, StefanIvanov requested changes

2021-01-04 15:50 UTC, StefanIvanov commented on en/components/snackbar.md
> +The Snackbar comes with styling flexibility, allowing to change the text color of the message and the action button, and the background color.
```suggestion
The Snackbar comes with styling flexibility, allowing to change the text color of the message, the action button, and the background color.
```

2021-01-07 10:29 UTC, StefanIvanov approved these changes

2021-01-08 10:47 UTC, sdimchevski approved these changes

2021-01-08 12:06 UTC, merged