Updated switch topic
IgniteUI/indigo-design-docfx pull request #412
Opened 2020-12-18 15:36 UTC by YoannaIvanova

2021-01-04 16:06 UTC, StefanIvanov requested changes

2021-01-04 16:06 UTC, StefanIvanov commented on en/components/switch.md
> +The Switch comes with styling flexibility, allowing control over the thumb and track colors, as well as change of the label text style color. There is a fixed alpha value applied to the track to make
```suggestion
The Switch comes with styling flexibility, allowing control over the thumb and track colors, as well as changing the label text color. The alpha value of the track is fixed to achieve a semi-transparent look no matter what color is used and can only be adjusted globally through the `Symbol Master` that can be found on the 🧩 Components page in the Indigo.Design library.```

2021-01-04 16:06 UTC, StefanIvanov commented on en/components/switch.md
> +The Switch supports a label position where the Switch label is placed after or before the Switch element.
```suggestion
The Switch supports a label position where the Switch label is placed before or after the Switch element.
```

2021-01-07 10:31 UTC, StefanIvanov approved these changes

2021-01-08 10:57 UTC, sdimchevski commented on en/components/switch.md
> +The Switch comes with styling flexibility, allowing control over the thumb and track colors, as well as changing the label text color. The alpha value of the track is fixed to achieve a semi-transpar
```suggestion
The Switch comes with styling flexibility, allowing control over the thumb and track colors, as well as changing the label text color. The alpha value of the track is fixed to achieve a semi-transparent look no matter what color is used and can only be adjusted globally through the `Symbol Master` that can be found on the 🧩 Components page in the Indigo.Design library.
```

2021-01-08 10:59 UTC, sdimchevski requested changes
Please remove ``` after library.

2021-01-08 11:40 UTC, sdimchevski approved these changes

2021-01-08 12:05 UTC, merged