Updated tabs topic
IgniteUI/indigo-design-docfx pull request #413
Opened 2020-12-20 16:14 UTC by YoannaIvanova

2021-01-07 13:17 UTC, StefanIvanov requested changes

2021-01-07 13:17 UTC, StefanIvanov commented on en/components/tabs.md
> +## Short Bar Tabs Content
```suggestion
## Short Bar Content
```

2021-01-07 13:17 UTC, StefanIvanov commented on en/components/tabs.md
> +The short bar comes with **label** tabs but if you want to describe the tabs with an icon instead you have to set the label of each tab to ~No Symbol.
```suggestion
The short bar comes with text content by default and if you want to show an icon instead, you have to assign a Material Icon to the `🔣 Icon` override and set the `🏷️ Label` to ~No Symbol for every tab in the bar.
```

2021-01-07 13:17 UTC, StefanIvanov commented on en/components/tabs.md
> +The Tabs consists of tabs that support Active, Inactive and Disabled states. In Tabs there is always one Active tab and an arbitrary number of Inactive and Disabled ones.
```suggestion
## Tab Item State

Tab items support Active, Inactive and Disabled states. In Tabs there is always one Active tab and an arbitrary number of Inactive and Disabled ones.
```

2021-01-07 13:33 UTC, StefanIvanov requested changes

2021-01-07 13:33 UTC, StefanIvanov commented on en/components/tabs.md
> +For the majority of scenarios, the Tabs need to contain between two and four tabs. You can exclude a tab by setting it to ~No Symbol. If your case requires more tabs, you may want to consider a fluid
```suggestion
For the majority of scenarios, the Tabs need to contain between two and five tabs. You can remove a tab item by setting it to ~No Symbol. If your case requires more tabs, you may want to consider a fluid mode and represent only the tabs in view.
```

2021-01-07 13:33 UTC, StefanIvanov commented on en/components/tabs.md
add an image with five tabs

2021-01-07 13:33 UTC, StefanIvanov commented on en/components/tabs.md
>  <img class="responsive-img" src="../images/tabs_fluid.png" srcset="../images/tabs_fluid@2x.png 2x" />
the fluid image looks broken

2021-01-08 11:23 UTC, StefanIvanov approved these changes

2021-01-08 11:39 UTC, sdimchevski approved these changes

2021-01-08 12:05 UTC, merged