Updating dropdown topic
IgniteUI/indigo-design-docfx pull request #417
Opened 2021-01-11 11:10 UTC by YoannaIvanova

2021-01-15 12:24 UTC, StefanIvanov commented on en/components/dropdown.md
> +Use the Dropdown Component to let the user select an item from a collection that is displayed upon user interaction in a scrollable list. Only one item can be selected at a time and if your scenario
```suggestion
Use the Dropdown Component to let the user select an item from a collection that is displayed upon user interaction in a scrollable list. Only one item can be selected at a time and if your scenario requires the selection of multiple items, you should use the [Combo](combo.md) instead. The Dropdown is visually identical to the [Ignite UI for Angular Dropdown Component](https://www.infragistics.com/products/ignite-ui-angular/angular/components/drop_down.html)
```

2021-01-15 12:29 UTC, StefanIvanov commented on en/components/dropdown.md
> +The Dropdown items support five different states: disabled, **idle**, focused, selected and selected&focused.
```suggestion
The Dropdown items support five different states: Disabled, **Idle**, Focused, Selected and Selected&focused.
```

2021-01-15 12:30 UTC, StefanIvanov commented on en/components/dropdown.md
> +When using the Dropdown you should always show it on top of the content that follows the item which triggers its display. Dropdowns don't push content like accordions do.
```suggestion
When using the Dropdown you should always show it on top of the content that follows the item which triggers its display. Dropdowns don't push content like an expansion panel would.
```

2021-01-15 12:34 UTC, StefanIvanov requested changes

2021-01-15 12:34 UTC, StefanIvanov commented on en/components/dropdown.md
> +<img class="responsive-img" src="../images/dropdown_item_idle.png" srcset="../images/dropdown_item_idle@2x.png 2x" />
add a second image with both icon and label

2021-01-18 16:15 UTC, StefanIvanov requested changes

2021-01-18 16:15 UTC, StefanIvanov commented on en/components/dropdown.md
> +<img class="responsive-img" src="../images/dropdown_item_idle.png" srcset="../images/dropdown_item_idle@2x.png 2x" />
only adding a second image here seems to be left and I will approve the changes

2021-01-19 08:00 UTC, StefanIvanov approved these changes

2021-01-19 13:50 UTC, sdimchevski approved these changes

2021-01-20 12:58 UTC, merged