Updating input topic
IgniteUI/indigo-design-docfx pull request #418
Opened 2021-01-11 15:42 UTC by YoannaIvanova

2021-01-15 13:24 UTC, StefanIvanov requested changes

2021-01-15 13:24 UTC, StefanIvanov commented on en/components/input.md
> +The Input has rich support for prefix and suffix through text string or icon that can, in certain cases, reduce the input effort for the user: e.g. an @email.com suffix means both less keystrokes and
```suggestion
The Input has rich support for prefix and suffix through a combination of text and icons that can, in certain cases, reduce the input effort for the user: e.g. an @email.com suffix means both fewer keystrokes and more clarity of expected content. You can remove the prefix or suffix by setting the respective container to ~No Symbol from the overrides.
```

2021-01-15 13:24 UTC, StefanIvanov commented on en/components/input.md
>  The Input comes with styling achievable through changing the primary, success, warning, and error colors of your theme in the Styling library.
```suggestion
The Input comes with styling flexibility through the colors of its background and bottom line, as well as icon color and text styles of its prefix, suffix, and main areas of content. To change the validation styles, it is recommended to update the respective color variables in the Indigo.Design library. 
```

2021-01-19 08:48 UTC, StefanIvanov requested changes

2021-01-19 08:48 UTC, StefanIvanov commented on en/components/input.md
> +<img class="responsive-img" src="../images/input_simple.png" srcset="../images/input_simple@2x.png 2x" />
add below a border and box type

2021-01-19 09:42 UTC, StefanIvanov approved these changes

2021-01-19 13:58 UTC, sdimchevski commented on en/components/input.md
>  The Input can be used styled in **dark** and light variants to assure good readability and contrast for both lighter and darker backgrounds.
```suggestion
The Input can be styled in **dark** and light variants to assure good readability and contrast for both lighter and darker backgrounds.
```

2021-01-19 15:55 UTC, sdimchevski approved these changes

2021-01-20 12:55 UTC, merged