Updating list topic
IgniteUI/indigo-design-docfx pull request #421
Opened 2021-01-13 12:44 UTC by YoannaIvanova

2021-01-15 14:05 UTC, StefanIvanov requested changes

2021-01-15 14:05 UTC, StefanIvanov commented on en/components/list.md
> +| Checkbox         | <img class="responsive-img" src="../images/list_item_secondary2.png" srcset="../images/list_item_secondary2@2x.png 2x" /> | Checkbox in a Secondary Action can not have a label, t
```suggestion
| Checkbox         | <img class="responsive-img" src="../images/list_item_secondary2.png" srcset="../images/list_item_secondary2@2x.png 2x" /> | Checkbox in a Secondary Action can not have a label, therefore, the before and after labels are set to ~No Symbol and this setting should not be changed |
```

2021-01-15 14:05 UTC, StefanIvanov commented on en/components/list.md
> +| Toggle             | <img class="responsive-img" src="../images/list_item_secondary4.png" srcset="../images/list_item_secondary4@2x.png 2x" /> | Switch in a Secondary Action can not have a label, t
```suggestion
| Toggle             | <img class="responsive-img" src="../images/list_item_secondary4.png" srcset="../images/list_item_secondary4@2x.png 2x" /> | Switch in a Secondary Action can not have a label, therefore, the before and after labels are set to ~ No Symbol and this setting should not be changed                                                                                                                 |
```

2021-01-15 14:05 UTC, StefanIvanov commented on en/components/list.md
> +
Assuming that you want to tell about the list patterns let's remove this from here and @sdimchevski will describe all list presets available as patterns in that topic.

2021-01-15 14:05 UTC, StefanIvanov commented on en/components/list.md
> +
```suggestion
```

2021-01-15 14:07 UTC, StefanIvanov commented on en/components/list.md
```suggestion
```

2021-01-18 13:50 UTC, StefanIvanov commented on en/components/list-skeleton.md
> +_description: The Skeleton List is a representation of a List component that is shown while data is being loaded in the background to provide content for a list.
```suggestion
_description: The Skeleton List is a representation of a List component that is shown while data is being loaded in the background to provide content for its items.
```

2021-01-18 13:51 UTC, StefanIvanov commented on en/components/list-skeleton.md
> +| Checkbox + Label               | <img class="responsive-img" src="../images/list_skeleton_item_primary2.png" srcset="../images/list_skeleton_item_primary2@2x.png 2x" />   |  Checkbox in a Secondary
```suggestion
| Checkbox + Label               | <img class="responsive-img" src="../images/list_skeleton_item_primary2.png" srcset="../images/list_skeleton_item_primary2@2x.png 2x" />   |  Checkbox in a Primary Action can not have a label, therefore, the before and after labels are set to ~No Symbol and this setting should not be changed |
```

2021-01-18 14:04 UTC, StefanIvanov requested changes

2021-01-18 14:04 UTC, StefanIvanov commented on en/components/list-custom.md
> +1.  First, we have to remove the paragraph and footer. Then we will reuse the Header from the Primary Action Group but resize it to fit in the right half only and update the strings for the Title and
```suggestion
1.  First, we have to remove the paragraph and footer. Then we will reuse the Header from the Primary Action Group but resize it to fit in the right half only and update the strings for the Title and Subtitle Text. In the Secondary Action Group, we will add a Raised Button, position it near the bottom right corner, updating its text and resize it accordingly to fit the new value. Lastly, let's remove the default Secondary Action, as we will not be needing Icons for our target custom layout.
```

2021-01-18 14:04 UTC, StefanIvanov commented on en/components/list-custom.md
> +2.  Next, we will insert a List/Custom/Blocks/Image Content in the Primary Action Group and add a Badge on top of it within the same group. Now, we have to size the image according to the Item size a
```suggestion
2.  Next, we will insert a List/Custom/Blocks/Image Content in the Primary Action Group and add a Badge on top of it within the same group. Now, we have to size the image according to the Item size and select content for it. After modifying the Badge, updating its Value Text, and setting its Elevation to None, we should have something similar to this.
```

2021-01-18 16:12 UTC, StefanIvanov approved these changes

2021-01-19 16:36 UTC, sdimchevski approved these changes

2021-01-20 12:55 UTC, merged