Updating grid topic
IgniteUI/indigo-design-docfx pull request #428
Opened 2021-01-18 08:26 UTC by YoannaIvanova

2021-01-22 14:33 UTC, StefanIvanov requested changes

2021-01-22 14:33 UTC, StefanIvanov commented on en/components/grid-grouping.md
> +The Grid has a `GroupBy Row` symbol under `Features` that represents a special row in the Grid that is like a heading preceding the grouped records with some summary information about their amount wi
```suggestion
The Grid has a `GroupBy Row` symbol under `Features` that represents a special row in the Grid that is like a heading preceding the grouped records with some summary information about their amount within the group. Adding this symbol has only a visual effect on your design to make it more realistic. To switch the GroupBy feature on, insert and configure a `Group Area`.
```

2021-01-22 14:33 UTC, StefanIvanov commented on en/components/grid-excel-style-filter.md
> +- [Grid Display Density](grid-display-density.md)
```suggestion
- [Grid Row Filter](grid-row-filter.md)
- [Grid Display Density](grid-display-density.md)
```

2021-01-22 14:33 UTC, StefanIvanov commented on en/components/grid-summaries.md
>  <img class="responsive-img" src="../images/grid_summaries_styling.png" srcset="../images/grid_summaries_styling@2x.png 2x" />
@YoannaIvanova Make a new image where both available and unavailable summary cells have the same background color. The current image looks broken.

2021-01-22 14:33 UTC, StefanIvanov commented on en/components/grid-toolbar.md
@YoannaIvanova I added one more section could you add an image that has a different layout and elements of the toolbar from the default configuration,

2021-01-22 15:22 UTC, StefanIvanov commented on en/components/grid-skeleton.md
> +Use the Skeleton Grid Component to layout the same type of information that you would in the standard one, but to also indicate an application state when no data is present at the moment e.g. when da
```suggestion
Use the Skeleton Grid to layout the same type of information that you would in the standard one, but to also indicate an application state when no data is present at the moment e.g. when data is loaded from a remote data source and there is either lack of connectivity, or it takes some time. The Skeleton Grid is just a visual representation of a [Grid](grid.md) with a known layout, but without any data to show.
```

2021-01-22 15:22 UTC, StefanIvanov commented on en/components/grid-skeleton.md
> +The Skeleton Grid supports the same different feature configurations via the `Feature Left` and `Feature Right` overrides as the standard [Grid](grid.md).
```suggestion
The Skeleton Grid supports the same feature configurations via the `Feature Left` and `Feature Right` overrides as the standard [Grid](grid.md).
```

2021-01-25 12:23 UTC, StefanIvanov approved these changes

2021-01-25 12:24 UTC, StefanIvanov commented
@sdimchevski we are ready with the reviews of this set of topics so you may go ahead with the testing :)

2021-01-25 16:11 UTC, sdimchevski approved these changes

2021-01-25 16:32 UTC, merged