docs(vs-code-extension): Change topic to explain installing from marketplace
IgniteUI/indigo-design-docfx pull request #474
Opened 2021-03-09 17:09 UTC by dkamburov

closes #346

2021-03-10 08:27 UTC, StefanIvanov requested changes

2021-03-10 08:27 UTC, StefanIvanov commented on en/codegen/installing-vs-code-extension.md
> +2.  In the Extensions pane, in the search for the extensions in Marketplace, type the following "Infragistics Indigo.Design".
```suggestion
2.  In the Extensions pane, in the `Search Extensions in Marketplace` field, type the following "Infragistics Indigo.Design".
```

2021-03-10 09:07 UTC, StefanIvanov approved these changes

2021-03-11 19:27 UTC, ChronosSF approved these changes

2021-03-18 12:01 UTC, merged