Update content for Sketch plugin with Create App story
IgniteUI/indigo-design-docfx pull request #572
Opened 2021-11-01 16:43 UTC by hanastasov

Closes https://github.com/IgniteUI/indigo-design-docfx/issues/571

2021-11-02 09:20 UTC, StefanIvanov commented on en/sync-themes-plugin.md
> +-  quickly create an app in Indigo.Design AppBuilder. This app follows the structure of the Sketch design, mapping any symbol from the Indigo.Design UI kit to the corresponding component from Ignite
```suggestion
-  quickly create an app in Indigo.Design AppBuilder. This app follows the structure of the Sketch design, mapping any symbol from the Indigo.Design UI kit to the corresponding component from Ignite UI. The plugin also takes the images used in Sketch and uploads them in the Assets library under AppBuilder, benefiting from [`Assets` support](https://www.infragistics.com/community/blogs/b/jason_beres/posts/indigo-design-app-builder-october-release-with-assets-support).  
```

2021-11-02 09:25 UTC, StefanIvanov commented on en/sync-themes-plugin.md
> +### 2. Publishing new prototype
```suggestion
### Publishing new prototype
```

2021-11-02 09:26 UTC, StefanIvanov commented on en/sync-themes-plugin.md
> +### 3. Update an existing prototype
```suggestion
### Update an existing prototype
```

2021-11-02 09:26 UTC, StefanIvanov commented on en/sync-themes-plugin.md
> +## 2.
```suggestion
## 2. Create an application in AppBuilder
Take your designs and get interactive, responsive app with real UI components and styling. Use the `Create App` tab and the plugin will transform your Sketch design into a real application under the AppBuilder, allowing access to the images and themes that you have used in Sketch - all of this directly in the cloud.

The plugin allows you to choose a name and resolution for your app, as well as choosing your Indigo.Cloud workspace, where to have the app created.

<img class="responsive-img" src="images/create-from-sketch.gif" srcset="images/create-from-sketch.gif 2x" />
```

2021-11-02 09:28 UTC, StefanIvanov requested changes
I moved a few things around and feel that it is better this way. Aside from that the content you added looks great. Do you think we should also update the rest of the images with the new looks and design?

Thanks! Updating the rest of the images should happen once the plugin is there with the new screens, so let's postpone it for that moment.

2021-11-02 09:34 UTC, hanastasov commented
> I moved a few things around and feel that it is better this way. Aside from that the content you added looks great. Do you think we should also update the rest of the images with the new looks and design?

Thanks! Updating the rest of the images should happen once the plugin is there with the new screens, so let's postpone it for that moment.

2021-11-02 09:53 UTC, StefanIvanov approved these changes

2021-11-02 10:17 UTC, hanastasov commented
Closing in favour of #573

2021-11-22 12:13 UTC, StefanIvanov approved these changes

2021-11-22 12:16 UTC, zdrawku approved these changes

2021-11-22 12:16 UTC, merged