Grid Toolbar Update
IgniteUI/indigo-design-docfx pull request #722
Opened 2023-04-25 12:34 UTC by IGSvt

-Reference image update
-Adding info regarding Figma

2023-05-09 08:00 UTC, imincheva requested changes
Images need to be updated.

2023-05-09 08:00 UTC, imincheva commented on en/images/grid_toolbar_demo.png
There's a transparent stripe between the grid and the toolbar.

2023-05-09 08:00 UTC, imincheva commented on en/images/grid_toolbar_demo@2x.png
There's a transparent stripe between the grid and the toolbar.

2023-05-09 08:00 UTC, imincheva commented on en/images/grid_toolbar_styling.png
There's a transparent stripe between the grid and the toolbar.

2023-05-09 08:00 UTC, imincheva commented on en/images/grid_toolbar_styling@2x.png
There's a transparent stripe between the grid and the toolbar.

2023-05-09 08:00 UTC, imincheva commented on en/images/grid_toolbar_layout.png
There's empty space on the image, which is transparent.

2023-05-09 08:00 UTC, imincheva commented on en/images/grid_toolbar_layout@2x.png
There's empty space on the image, which is transparent.

2023-05-10 07:09 UTC, IGSvt commented on en/images/grid_toolbar_layout.png
thats on purpose so the image has same size as all the references

2023-05-10 07:15 UTC, IGSvt commented on en/images/grid_toolbar_layout.png
I have changed it however this is done so the images used for reference appear with the same scale

2023-05-10 12:50 UTC, imincheva submitted a review, later dismissed

2023-05-12 12:10 UTC, sdimchevski approved these changes

2023-05-12 12:10 UTC, merged