Grid Export Update
IgniteUI/indigo-design-docfx pull request #723
Opened 2023-04-25 13:16 UTC by IGSvt

-Adding keywords for Figma
-Replacing old reference image

2023-05-09 08:03 UTC, imincheva requested changes

2023-05-09 08:03 UTC, imincheva commented on en/images/grid_export_demo.png
There's a transparent stripe between the toolbar and the grid.

2023-05-09 08:03 UTC, imincheva commented on en/images/grid_export_demo@2x.png
There's a transparent stripe between the toolbar and the grid.

2023-05-10 12:51 UTC, imincheva approved these changes

2023-05-12 12:13 UTC, sdimchevski approved these changes

2023-05-12 12:13 UTC, merged