Grid-Group By Update
IgniteUI/indigo-design-docfx pull request #724
Opened 2023-04-26 08:01 UTC by IGSvt

- Updated image reference
- Updated keywords
- Updated definitions

2023-05-09 08:18 UTC, imincheva requested changes
I suggested one change on the text and left comments about the images.

2023-05-09 08:18 UTC, imincheva commented on en/images/grid_group_by_demo.png
There's excess space underneath the grid, which is transparent.

2023-05-09 08:18 UTC, imincheva commented on en/images/grid_group_by_demo@2x.png
There's excess space underneath the grid, which is transparent.

2023-05-10 07:28 UTC, IGSvt commented on en/components/grid-grouping.md
> +The Grid has a `GroupBy Row` symbol/component under `Grid Features` that represents a special row in the Grid that is like a heading preceding the grouped records with some summary information about
You are right

2023-05-10 12:52 UTC, imincheva approved these changes

2023-05-12 12:19 UTC, sdimchevski approved these changes

2023-05-12 12:19 UTC, merged