Grid Column Filtering Update
IgniteUI/indigo-design-docfx pull request #735
Opened 2023-04-28 11:25 UTC by IGSvt

-Updated keywords
-Adding info about Figma
-Updated image reference

2023-05-10 10:14 UTC, imincheva requested changes
You're missing Figma keywords. I also left a comment about inaccuracy in the description. Before making changes, please pull the commit I made beforehand.

2023-05-10 10:14 UTC, imincheva commented on en/components/grid-row-filter.md
> +The Row Filter Header Cells come with a `Filter State` override in Sketch that lets you configure whether a filtering condition has been applied on a given column. By default, it shows **Empty**, but
The description of row filtering is inaccurate. There's no "default" type of header cell and the types are called "Row Filter Filtered" and "Row Filter Empty".

2023-05-11 14:46 UTC, imincheva requested changes
You're still missing Figma keywords

2023-05-12 08:20 UTC, imincheva approved these changes

2023-05-12 12:48 UTC, sdimchevski approved these changes

2023-05-12 12:48 UTC, merged