Grid Summaries Update
IgniteUI/indigo-design-docfx pull request #743
Opened 2023-05-02 16:22 UTC by IGSvt

-Updated keywords
-Added info about Figma
-Updated reference images

2023-05-10 14:15 UTC, imincheva requested changes

2023-05-10 14:15 UTC, imincheva commented on en/components/grid-summaries.md
> +The Grid Summary Cell supports the following interactive states: **available** which shows a summary Label and Number and unavailable which is used to fill the gaps when one column has fewer Summarie
You should write the info for Figma separately because the `Component States` paradigm isn't relevant for Figma

2023-05-10 14:15 UTC, imincheva commented on en/images/grid_summaries_styling.png
Text in summary cells is red on the old images. I think it looks better and also the borders are visible.

2023-05-10 14:15 UTC, imincheva commented on en/images/grid_summaries_styling@2x.png
Text in summary cells is red on the old images. I think it looks better and also the borders are visible.

2023-05-11 08:22 UTC, imincheva submitted a review, later dismissed

2023-05-12 15:11 UTC, sdimchevski requested changes
Please update grid_cell_summary_active and grid_cell_summary_unavailable images

2023-05-12 17:59 UTC, sdimchevski approved these changes

2023-05-12 17:59 UTC, merged