Grid Skeleton Update
IgniteUI/indigo-design-docfx pull request #744
Opened 2023-05-03 07:36 UTC by IGSvt

-Updated keywords
-Updated reference images

2023-05-10 14:21 UTC, imincheva requested changes
I left a comment on the text. You should also replace the images, because there's a lot of empty space on most images

2023-05-10 14:21 UTC, imincheva commented on en/components/grid-skeleton.md
> +Currently, we don't support the Rating component in Figma.
Why does it say Rating component?

2023-05-12 06:29 UTC, imincheva approved these changes

2023-05-12 15:13 UTC, sdimchevski approved these changes

2023-05-12 15:13 UTC, merged