Calendar: Update
IgniteUI/indigo-design-docfx pull request #821
Opened 2024-10-11 13:20 UTC by imincheva

- Images have been updated
- Multi view in vertical orientation has been added

2024-10-21 13:08 UTC, yradoeva requested changes
Let's update the calendar_selection image to be without a header to reflect the implementation.

2024-10-21 14:00 UTC, yradoeva submitted a review, later dismissed

2024-10-25 10:17 UTC, sdimchevski requested changes

2024-10-25 10:30 UTC, sdimchevski requested changes

2024-10-25 10:30 UTC, sdimchevski commented on en/images/calendar_do1@2x.png
Title should be May 15 - May 17

2024-10-25 10:30 UTC, sdimchevski commented on en/images/calendar_dont1.png
Title should be May 15 - May 17

2024-10-25 11:56 UTC, sdimchevski approved these changes

2024-10-25 11:57 UTC, merged