Combo & Simple Combo: Update
IgniteUI/indigo-design-docfx pull request #823
Opened 2024-10-14 11:31 UTC by imincheva

- Images have been updated to reflect visual changes
- Removed selected + disabled state from dropdown on Simple Combo page

2024-10-24 08:23 UTC, yradoeva approved these changes

2024-10-25 16:34 UTC, sdimchevski requested changes

2024-10-25 16:34 UTC, sdimchevski commented on en/images/combo_styling.png
Input should have only Belarus. Please remove Belgium

2024-10-28 14:00 UTC, sdimchevski approved these changes

2024-10-28 14:00 UTC, merged