Input: Update
IgniteUI/indigo-design-docfx pull request #824
Opened 2024-10-14 12:03 UTC by imincheva

- Input states have been updated
- Images have been updated to reflect the visual changes

2024-10-24 06:57 UTC, yradoeva approved these changes

2024-10-24 15:51 UTC, sdimchevski requested changes

2024-10-24 15:51 UTC, sdimchevski commented on en/images/input_warning.png
Name should be just John

2024-10-24 15:51 UTC, sdimchevski commented on en/images/input_error.png
John Smith should be just Jo to indicate the error

2024-10-25 07:36 UTC, yradoeva approved these changes

2024-10-25 16:04 UTC, sdimchevski approved these changes

2024-10-25 16:04 UTC, merged