Navigation Drawer: Update
IgniteUI/indigo-design-docfx pull request #826
Opened 2024-10-14 12:59 UTC by imincheva

- Images have been updated to reflect the visual changes
- Disabled state has been added
- Info about Icon boolean property has been added

2024-10-24 13:34 UTC, yradoeva approved these changes

2024-10-25 12:12 UTC, sdimchevski requested changes

2024-10-25 12:12 UTC, sdimchevski commented on en/images/nav-drawer_do3@2x.png
Let's change Secondary Text to California

2024-10-25 15:48 UTC, sdimchevski requested changes

2024-10-25 15:48 UTC, sdimchevski commented on en/images/nav-drawer_do3.png
The smaller size of the image still says Secondary Text

2024-10-28 08:01 UTC, sdimchevski approved these changes

2024-10-28 08:01 UTC, merged