Select: Update
IgniteUI/indigo-design-docfx pull request #833
Opened 2024-10-16 14:27 UTC by yradoeva

- updated all images with drop down because of the roundness
- fixed the broken image in the Layout section by renaming it
- removed selected & disabled state in drop down item states
- changed the select_enabledstate png to idle state (was filled)

2024-10-21 11:10 UTC, imincheva requested changes
I believe we missed to change Drop Down to Dropdown during the last documentation update, so you can add it here. 

@sdimchevski 
Additionally, I've noticed that the description of the dropdown is a bit misleading - it's not a separate dropdown we explicitly use in the Select (contrary to the Combo, where we have a separate dropdown), but a standalone dropdown component. IMO we can remove the info about the dropdown as a whole and just refer to the dropdown page or at least paraphrase the first sentence in Drop Down Item section, so it's not misleading.

2024-10-23 08:32 UTC, imincheva submitted a review, later dismissed

2024-10-25 16:16 UTC, sdimchevski requested changes

2024-10-25 16:16 UTC, sdimchevski commented on en/images/select_box.png
Label should say Pick a car

2024-10-28 08:12 UTC, imincheva approved these changes

2024-10-28 14:03 UTC, sdimchevski approved these changes

2024-10-28 14:03 UTC, merged