Date Picker: Update
IgniteUI/indigo-design-docfx pull request #836
Opened 2024-10-17 15:21 UTC by yradoeva

- updated the images because of visual change of the date picker
- included Action Buttons in the Picker layout text (only in Figma)
- added section Multiview variants with text and some images to show them in Figma; for Sketch and XD we have multiview only in horizontal view

2024-10-21 11:29 UTC, imincheva submitted a review, later dismissed

2024-10-25 16:46 UTC, sdimchevski requested changes

2024-10-25 16:46 UTC, sdimchevski commented on en/images/datepicker_actions.png
Title should say 2021

2024-10-25 16:46 UTC, sdimchevski commented on en/images/datepicker_do1.png
Title should say 2021

2024-10-25 16:46 UTC, sdimchevski commented on en/images/datepicker_dont1.png
Title should say 2021

2024-10-25 16:46 UTC, sdimchevski commented on en/images/datepicker_horizontal.png
Title should say 2021

2024-10-25 16:46 UTC, sdimchevski commented on en/images/datepicker_multi_horiz.png
Title should say 2021

2024-10-25 16:46 UTC, sdimchevski commented on en/images/datepicker_multi_vert.png
Title should say 2021

2024-10-25 16:46 UTC, sdimchevski commented on en/images/datepicker_styling.png
Title should say 2021

2024-10-25 16:46 UTC, sdimchevski commented on en/images/datepicker_vertical.png
Title -> 2021

2024-10-28 08:11 UTC, imincheva approved these changes

2024-10-28 14:07 UTC, sdimchevski approved these changes

2024-10-28 14:07 UTC, merged